### ISSUE TITLE
Remove references to CustomTaskList stock plugin component

### ISSUE THREAD

**Issue by trogers-twilio** [ldvlgr/pause-recording#1]
https://github.com/ldvlgr/pause-recording/blob/380027da82910a7823c38d0cb192a979347bf103/pause-recording-plugin/src/PauseRecordingPlugin.js#L5

https://github.com/ldvlgr/pause-recording/blob/380027da82910a7823c38d0cb192a979347bf103/pause-recording-plugin/src/states/index.js#L3

https://github.com/ldvlgr/pause-recording/blob/380027da82910a7823c38d0cb192a979347bf103/pause-recording-plugin/src/states/index.js#L11

https://github.com/ldvlgr/pause-recording/blob/main/pause-recording-plugin/src/states/CustomTaskListState.js

https://github.com/ldvlgr/pause-recording/tree/main/pause-recording-plugin/src/components/CustomTaskList

https://github.com/ldvlgr/pause-recording/tree/main/pause-recording-plugin/src/components/__tests__

**Comment by ldvlgr** [comment]
Done
